name: orderapp
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  toastification: ^3.0.1
  connectivity_plus: ^6.1.3
  lottie: ^3.3.1
  permission_handler: ^11.4.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/lottie/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Regular.otf